matrix:
    PYTHON_VERSION:
        - 3.5.5
        - 3.6.6
        - 3.7.0

pipeline:
    build:
        image: nathanhoad/gbulb-python:${PYTHON_VERSION}
        commands:
            - python setup.py install
            - pytest
