name: Upload Python Package

on:
  release:
    types: published

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      # This permission is required for trusted publishing.
      id-token: write
    steps:
    - uses: actions/checkout@v4.1.4

    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: "3.x"

    - name: Install dependencies
      run: |
        sudo apt install -y pkg-config python3-dev libgirepository1.0-dev gir1.2-gtk-3.0
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install tox

    - name: Build release artefacts
      run: |
        tox -e package

    - name: Publish release
      uses: pypa/gh-action-pypi-publish@release/v1
